Resolve `compiler_flags` to allow Mac build (#3478)
Summary:
Pull Request resolved: https://github.com/pytorch/executorch/pull/3478

## `-Wglobal-constructors`

In ET-Vulkan, we use global constructors without global destructors.

Example: [`auto cls = VulkanBackend();`](https://github.com/pytorch/executorch/blob/242b75d328d5300481a02447067d2507a2983e26/backends/vulkan/runtime/VulkanBackend.cpp#L511-L513)
```
xplat/executorch/backends/vulkan/runtime/VulkanBackend.cpp:511:6: error: declaration requires a global destructor [-Werror,-Wglobal-constructors]
auto cls = VulkanBackend();
     ^
```

On Mac, this results in a `-Wglobal-constructors` warning, which is disabled in this change.

## `-Wmissing-prototypes`
## `-Wshadow`

Same as https://github.com/pytorch/pytorch/pull/125361

Reviewed By: SS-JIA

Differential Revision: D56860764

fbshipit-source-id: 5e598a3774c04e9f4b4911cc7cbda14dbe703fd8