Bump macOS deployment target to 12.0 (#11247)
### Summary

We want to enable MPS AOT for macOS. This requires a minimum target
deployment of 12.0. Example error:

```
2025-05-30T01:57:11.3334050Z /Users/runner/work/executorch/executorch/pytorch/executorch/backends/apple/mps/runtime/MPSGraphBuilder.mm:174:1: error: 'MPSGraphExecutable' is only available on macOS 12.0 or newer [-Werror,-Wunguarded-availability-new]
2025-05-30T01:57:11.3334100Z MPSGraphExecutable*
2025-05-30T01:57:11.3334140Z ^
```

Given 12.0 is already [at end of
life](https://en.wikipedia.org/wiki/MacOS_version_history), are there
any other problems with this increase?

### Test plan

```
rg "10(\.|_)15" --hidden -g '!**/{third-party,.git}'
```