Arm backend: Fix numerical accuracy error. (#13578)
A missing .graph caused numerical errors to show up as "AttributeError:
'GraphModule' object has no attribute 'output_node'"

Signed-off-by: Adrian Lundell <adrian.lundell@arm.com>